name: jobs_crud_app
description: Simple app that creates, read, upload and delete data from Firebase. Its a list of jobs.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_riverpod: 2.5.1
  go_router: 14.1.1
  equatable: 2.0.5
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_ui_auth: ^1.15.0
  cloud_firestore: ^5.0.2
  faker: ^2.1.0
  firebase_ui_firestore: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
